### PR TITLE
POPF OT Implementation

### PR DESCRIPTION
**Pull request by ldr709**
This is the implementation of batched OTs based on Programmable Once Public Functions presented in https://eprint.iacr.org/2021/682. All OTs except for the assembly implementation of SimplestOT have been switched over to the libsodium library's implementation of curve25519, because it is much faster than Relic.

Depends on a [corresponding](https://github.com/ladnir/cryptoTools/pull/24) cryptoTools PR.

### CODE REVIEW

**Comment by ladnir** [comment]
Great! I'll take a look. Ive actually been talking to Diego (relic) and hes under the impression relic is the fastest library if properly configured. I'll consult with him some more and decide which is faster (sodium or properly configured relic). Either way, it will be nice having more than one option.

**Comment by ldr709** [comment]
It's possible that I've misconfigured Relic. The numbers I'm getting from a microbenchmark of 1000 variable base scalar multiplications is 168ms for Ed25519 vs 451ms for RCurve. Do you have a known good set of options to pass to Relic's `cmake`?

At the moment the PR changes it to only support libsodium, but I can probably add some preprocessor macros to make the existing base OTs work with either.

**Comment by ladnir** [comment]
I don't know. I'll ask Diego. I can cc you.

**Comment by ladnir** [comment]
So it seems he's adding a new curve which should be faster. 

Lets do this, we can add your new code but keep the existing code that uses relic. The major issue with removing/replacing relic is that it is a breaking change. If someone was using libOTe and updates it, this new version will not compile as before. Its best to only "add new features" unless there is a very good reason to break something, and then I would prefer to have a transition/deprecated period.

Would you be willing to rework the PR to achieve this?

Thanks

**Comment by ldr709** [comment]
I agree that it would be better to keep Relic. I'll make the necessary modifications, probably sometime in the next week or so.

**Comment by ldr709** [comment]
The MIRACL library seems to still be a possible elliptic curve implementation for SimplestOT and Noar-Pinkas, but it is no longer mentioned in the readme and seems to be missing from some parts of the cmake files. Is it alright to just keep Relic, or do you want to keep MIRACL as well? I'm asking because Rist25519 is a lot more compatible with RCurve than with MIRACL, so it seems that I need a lot more `#ifdef`s to keep MIRACL.

**Comment by ladnir** [comment]
Correct, we don't want to use/include any miracl code going forward. Let's just do relic.

**Comment by ldr709** [comment]
After making some [changes](https://github.com/ladnir/cryptoTools/pull/27) to the elliptic curve classes to make them more compatible, every base OT where it makes sense can now use either `RCurve` or `Rist25519`. Thank you for the prompt responses you have given me about what needed to be changed.

**Comment by ladnir** [comment]
merged. So it looks like you need some custom sodium version? Want to explain the situation? Is there a specific repo or configuration you need?

Want to add a way to pull the dependency like relic and boost.

**Pull request merged**
